#!/bin/bash
# Create directory from installed package and build it

#arm_cortex-a7_neon-vfpv4
NEW_LOADER="/lib/ld-musl-armhf.so.1"

patch_file()
{
  file_to_patch=${1}
  found_loader=$(patchelf --print-interpreter "${file_to_patch}" 2> /dev/null)
  if [ $? -eq 0 ]
  then
    echo "Found loader ${found_loader}"
    if [ ${found_loader} = "/lib/ld-musl-arm.so.1" ]
    then
      echo "Patching loader to point to $NEW_LOADER"
      patchelf --set-interpreter "$NEW_LOADER" "${file_to_patch}"
      if [ $? -eq 0 ]
      then
        echo "Successfully patched ${file_to_patch}!"
      fi
    fi
  fi
  found_libs=$(patchelf --print-needed "${file_to_patch}" 2> /dev/null)
  if [ $? -eq 0 ]
  then
    case "${found_libs}" in
      *"libubox.so"*)
        patchelf --replace-needed libubox.so libubox.so.20240329 "${file_to_patch}"
        echo "Successfully patched lib reference ${file_to_patch}!"
      ;;&
      *"libubus.so"*)
        patchelf --replace-needed libubus.so libubus.so.20231128 "${file_to_patch}"
        echo "Successfully patched lib reference ${file_to_patch}!"
      ;;&
      *"libblobmsg_json.so"*)
        patchelf --replace-needed libblobmsg_json.so libblobmsg_json.so.20240329 "${file_to_patch}"
        echo "Successfully patched lib reference ${file_to_patch}!"
      ;;&
    esac
  fi

  if grep --binary-files=without-match dlan2-2400-ac "${file_to_patch}" 2> /dev/null
  then
    sed -i 's/dlan2-2400-ac/devolo,magic-2-wifi-next/g' "${file_to_patch}"
    echo "Successfully patched model reference ${file_to_patch}!"
  fi
  if grep --binary-files=without-match '/sys/class/gpio/gpio63' "${file_to_patch}" 2> /dev/null
  then
    sed -i 's|/sys/class/gpio/gpio63|/sys/class/gpio/plc-enable|g' "${file_to_patch}" 2> /dev/null
    echo "Successfully patched gpio reference ${file_to_patch}!"
  fi
  if grep --binary-files=without-match 'ssdk_set_set_advertise 4' "${file_to_patch}" 2> /dev/null
  then
    sed -i 's/ssdk_set_set_advertise 4/ethtool -s ghn speed/g' "${file_to_patch}" 2> /dev/null
    echo "Successfully patched ssdk_set_set_advertise to ethtool ${file_to_patch}!"
  fi
}

usage="Usage: $0 [-v] [-h] [-m] <pkg_path> [<destination_directory>]"
case $# in
1)
	dest_dir=$PWD
	;;
2)
	dest_dir=$2
	if [ "$dest_dir" = "." ] || [ "$dest_dir" = "./" ] ; then
	    dest_dir=$PWD
	fi
	;;
*)
	echo "$usage" >&2
	exit 1
	;;
esac

tmp_dir=${dest_dir}/$(basename ${0}).$$

# This will be usr/lib/opkg/info/package[,.list,.control]
input_file="$(realpath "${1}")"
root_dir=$(dirname ${input_file})/../../../..

package_name=$(basename ${input_file})
config_result=$(grep "CONFIG_PACKAGE_${package_name}" ../.config)
if [ $? -eq 0 ]
then
  case "${config_result}" in
    *"is not set"*)
      echo "Please use the OpenWRT package"
      echo "Enable ${package_name} in 'make menuconfig'"
    ;;
  esac
  exit 0
fi
mkdir -p ${tmp_dir}/CONTROL
cp ${input_file}.control ${tmp_dir}/CONTROL/control
sed -i 's/Architecture: ipq/Architecture: arm_cortex-a7_neon-vfpv4/' ${tmp_dir}/CONTROL/control
if [ -e ${input_file}.conffiles ]
then
  cp ${input_file}.conffiles ${tmp_dir}/CONTROL/conffiles
fi

prev_dir=${PWD}
cd ${root_dir}
while read line
do
  cp -a --parents .${line} ${tmp_dir}/
  patch_file ${tmp_dir}/.${line}
done < ${input_file}.list
cd ${prev_dir}

prev_dir=${PWD}
cd ${dest_dir}
${prev_dir}/ipkg-build ${tmp_dir}
if [ $? -ne 0 ]
then
  exit 1
fi
cd ${prev_dir}
rm -r ${tmp_dir}
