#!/bin/sh

# Create directory from installed package and build it

NEW_LOADER="/lib/ld-musl-armhf.so.1"

patch_file()
{
  file_to_patch=${1}
  found_loader=$(patchelf --print-interpreter "${file_to_patch}" 2> /dev/null)
  if [ $? -eq 0 ]
  then
    echo "Found loader ${found_loader}"
  fi
  if [ ${found_loader} = "/lib/ld-musl-arm.so.1" ]
  then
    echo "Patching loader to point to $NEW_LOADER"
    patchelf --set-interpreter "$NEW_LOADER" "${file_to_patch}"
    if [ $? -eq 0 ]
    then
      echo "Successfully patched ${file_to_patch}!"
	fi
  fi
}

set -e
usage="Usage: $0 [-v] [-h] [-m] <pkg_path> [<destination_directory>]"
case $# in
1)
	dest_dir=$PWD
	;;
2)
	dest_dir=$2
	if [ "$dest_dir" = "." ] || [ "$dest_dir" = "./" ] ; then
	    dest_dir=$PWD
	fi
	;;
*)
	echo "$usage" >&2
	exit 1
	;;
esac

tmp_dir=${dest_dir}/$(basename ${0}).$$

# This will be usr/lib/opkg/info/package[,.list,.control]
input_file="$(realpath "${1}")"
root_dir=$(dirname ${input_file})/../../../..

mkdir -p ${tmp_dir}/CONTROL
cp ${input_file}.control ${tmp_dir}/CONTROL/control

prev_dir=${PWD}
cd ${root_dir}
while read line
do
  echo ${line}
  echo ${tmp_dir}
  cp -a --parents .${line} ${tmp_dir}/
  patch_file ${tmp_dir}/.${line}
done < ${input_file}.list
cd ${prev_dir}

./ipkg-build ${tmp_dir} ${dest_dir}
rm -r ${tmp_dir}
