#!/bin/bash

root_dir=$1
destination=$2

for package in ${root_dir}/usr/lib/opkg/info/*.list
do
  echo ${package}
  ./ipkg-build-from-installed ${package::-5} ${destination}
  if [ $? -ne 0 ]
  then
    exit 1
  fi
done
