#!/bin/sh

base_files_openwrt=${1}
root_dir=${2}
dest_dir=${3}

tmp_dir=${dest_dir}/$(basename ${0}).$$

mkdir -p "${tmp_dir}"/CONTROL
cp ${root_dir}/usr/lib/opkg/info/base-files.control "${tmp_dir}"/CONTROL/control
sed -i 's/Package: base-files/Package: base-files-downstream/' ${tmp_dir}/CONTROL/control
sed -i 's/Architecture: ipq/Architecture: arm_cortex-a7_neon-vfpv4/' ${tmp_dir}/CONTROL/control

prev_dir=${PWD}
cd ${root_dir}
while read line
do
  if ! grep --quiet ${line} ${base_files_openwrt}
  then
    cp -a --parents .${line} "${tmp_dir}"/
  fi
done < ${root_dir}/usr/lib/opkg/info/base-files.list
cd ${prev_dir}

rm "${tmp_dir}"/sbin/wifi

prev_dir=${PWD}
cd ${dest_dir}
${prev_dir}/ipkg-build ${tmp_dir}
if [ $? -ne 0 ]
then
  exit 1
fi
cd ${prev_dir}
rm -r ${tmp_dir}
